## MUHAMMAD AMIN NADIM
https://muhammad-amin-nadim.github.io/

## ADAPTIC BOOSTING TECHNIQUEJ (Ada-Boost Technique)

#### AdaBoost also called Adaptive Boosting is a technique in Machine Learning used as an Ensemble Method. The most common algorithm used with AdaBoost is decision trees with one level that means with Decision trees with only 1 split. These trees are also called Decision Stumps.

Importing Necessary Libraries:

In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn import datasets

## Loading the Dataset:

In [2]:
iris = datasets.load_iris()
X = iris.data
Y = iris.target

## Visualizing the Dataset:

In [3]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [4]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [5]:
iris.data[0:5]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

## Splitting the Dataset:

In [6]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3)

## Building the AdaBoost Model: 

In [7]:
from sklearn.ensemble import AdaBoostClassifier 
adb = AdaBoostClassifier()
model = adb.fit(X_train, Y_train)
y_pred = model.predict(X_test)
y_pred

array([2, 1, 2, 2, 0, 2, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 2, 2, 1, 2,
       2, 0, 1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 2, 0, 2, 0, 2, 1, 1, 2, 0, 0,
       2])

## Evaluating the Model

## a) Without Parameter Tuning:

In [8]:
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))
print(accuracy_score(Y_test, y_pred))

[[16  0  0]
 [ 0 12  1]
 [ 0  1 15]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.92      0.92      0.92        13
           2       0.94      0.94      0.94        16

    accuracy                           0.96        45
   macro avg       0.95      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45

0.9555555555555556


<hr></hr>

## b) After Parameter Tuning:
The most important parameters of AdaBoost are:
- base_estimator
- n_estimators
- learning_rate

In [9]:
"""Using SVM as a base estimator"""
from sklearn.svm import SVC
from sklearn.ensemble import AdaBoostClassifier 
svc = SVC(probability = True, kernel='linear')
adb = AdaBoostClassifier(n_estimators=100,base_estimator = svc, learning_rate= 0.01)

## Training and Predicting the AdaBoost Classifier

In [10]:
model = adb.fit(X_train, Y_train)
y_pred = model.predict(X_test)
y_pred

array([2, 1, 2, 2, 0, 2, 0, 0, 1, 1, 0, 2, 0, 0, 1, 1, 0, 1, 2, 2, 1, 2,
       2, 0, 1, 1, 0, 0, 0, 2, 1, 2, 0, 2, 2, 0, 2, 0, 2, 1, 1, 2, 0, 0,
       2])

## Evaluating the Model:

In [11]:
print(confusion_matrix(Y_test, y_pred))
print(classification_report(Y_test, y_pred))
print(accuracy_score(Y_test, y_pred))

[[16  0  0]
 [ 0 12  1]
 [ 0  0 16]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       1.00      0.92      0.96        13
           2       0.94      1.00      0.97        16

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.98        45
weighted avg       0.98      0.98      0.98        45

0.9777777777777777
